export default {
  "menu.index": "Home",
  "menu.system": "System Management",
  "menu.user": "User Management",
  "menu.role": "Role Management",
  "menu.terminal": "Device Management",
  "menu.reader": "Reader Management",
  "menu.search" : "Search",
  "menu.transaction" : "Transaction",
  "menu.update": "Update",
  "menu.device": "Device Management",
  "menu.reader-list": "Reader Management",
  "menu.device-list": "Device List",
  "menu.visitor": "Visitor Search",
  "menu.provider": "Provider Management",
  "menu.branch": "Branch Management",
  "menu.config-system": "Config system",
  "menu.update-device-service": "Update Device Service",
  "menu.license" : "License Management",
  "menu.citizenCard":"Citizen Identity Card",
  "menu.passPort":"Pass Port",
  // "menu.register":"Register visitor",
  "menu.register":"Register visitor",
  "menu.check-visitor":"Check Visitor",
  "menu.borrow": "Borrow Mangement",
  "menu.report":"Report",
  "menu.returnCard":"Visitor Card Borrow",
  "menu.card":"Visitor Card Management",
  "menu.inout":"Visitor History",
  "menu.enrollment":"Enrollment",
  "Visitor":"Visitor"
}
