export default {
    "menu.index": "Trang chủ",
    "menu.system": "Quản lý hệ thống",
    "menu.config-system": "Cấu hình hệ thống",
    "menu.update-device-service": "Cập nhật Device Service",
    "menu.user": "Quản lý người dùng",
    "menu.role": "Quản lý vai trò",
    "menu.device": "Quản lý thiết bị",
    "menu.visitor": "Thông kê khách",
    "menu.provider": "Quản lý đối tác",
    "menu.branch": "Quản lý chi nhánh",
    "menu.reader": "Quản lý đầu đọc",
    "menu.reader-list": "Danh sách đầu đọc",
    "menu.device-list": "Danh sách thiết bị",
    "menu.order": "Tạo ra bản chuyển đổi",
    "menu.search": "Tìm kiếm",
    "menu.update": "Chỉnh sửa",
    "menu.transaction-manager": "Quản lý giao dịch",
    "menu.license": "Quản lý license",
    "menu.citizenCard": "Thẻ CCCD",
    "menu.passPort": "Hộ chiếu",
    // "menu.register": "Đăng ký mượn thẻ",
    // "menu.register": "Đăng ký tham quan nhà máy",
    // "menu.register": "Tham quan nhà máy",
    "menu.register": "Đăng ký khách",
    "menu.returnCard": "Khách trả thẻ",
    "menu.report":"Báo cáo",
    "menu.card":"Quản lý thẻ visitor",
    "menu.inout":"Lịch sử ra vào",
    "Visitor":"Khách",
    "menu.check-visitor":"Kiểm tra thông tin khách"

}
