export default {
    "Đã kích hoạt": "Activated",
    "Chưa kích hoạt": "Not activated",
    "Khóa": "Lock",
    "Mất": "Lost",
    "Hỏng": "Damage",
    "Bị trục trặc":"Malfunctioned",
    "Đã xóa": "Deleted",
    "Online": "Online",
    "Offline": "Offline",
    "all":"All",
    "Kích hoạt thiết bị":"Activated device",
    "Kích hoạt mobile":"Activated mobile",
    "Lấy dữ liệu MoC":"Get data MoC",
    "Lấy Mrz":"Get Mrz",
    "Tạo template mặt":"Get template face",
    "Tạo template vân tay":"Get template fingerprint",
    "Xác thực SOD":"Authentic SOD",
    "Hoạt động":"Active",
    "Đã hủy":"Cancelled",
    "face": "Face",
    "finger": "Finger",
}
