// @ts-ignore
import { t } from "@/i18n";
import type { MenuItem } from "../../menutype";
export const role: MenuItem = {
  tag: "system:role",
  leaf: true,
  path: "/roles",
  type: "menu",
  isWhiteList: false,
  name: t("menu.role"),
  // icon: "el-icon-fa-users",
  children: [],
  permissions: [
    {
      tag: "system:role:search",
      type: "button",
      isWhiteList: false,
      name: t("option.query"),
      pattern: "/api/admin/roles",
      method: "GET",
    },
    {
      tag: "system:role:insert",
      type: "button",
      isWhiteList: false,
      name: t("option.add"),
      pattern: "/api/admin/roles",
      method: "POST",
    },
    {
      tag: "system:role:update",
      type: "button",
      isWhiteList: false,
      name: t("option.update"),
      pattern: "/api/admin/roles/{roleId}",
      method: "PUT",
    },
    {
      tag: "system:role:delete",
      type: "button",
      isWhiteList: false,
      name: t("option.delete"),
      pattern: "/api/admin/roles/{roleId}",
      method: "DELETE",
    },
    {
      tag: "system:role:assign-permission",
      type: "button",
      isWhiteList: false,
      name: t("option.assignPermission"),
      pattern: "/api/admin/roleperms/{roleId}",
      method: "PUT",
    },
    {
      tag: "system:role:select-role-permission",
      type: "button",
      isWhiteList: false,
      name: t("role.selectRolePermission"),
      pattern: "/api/admin/roleperms/{roleId}",
      method: "GET",
    },
    {
      tag: "system:role:sync-permission",
      type: "button",
      isWhiteList: false,
      name: t("role.syncPermission"),
      pattern: "/api/admin/permissions",
      method: "POST",
    },
  ],
};
// export default {
//   tag: "system:role",
//   leaf: true,
//   path: "/roles",
//   type: "menu",
//   isWhiteList: false,
//   name: t("menu.role"),
//   // icon: "el-icon-fa-users",
//   options: [
//     {
//       tag: "system:role:select",
//       type: "button",
//       isWhiteList: false,
//       name: t("option.query"),
//       pattern: "/api/admin/roles",
//       method: "GET",
//     },
//     {
//       tag: "system:role:insert",
//       type: "button",
//       isWhiteList: false,
//       name: t("option.add"),
//       pattern: "/api/admin/roles",
//       method: "POST",
//     },
//     {
//       tag: "system:role:update",
//       type: "button",
//       isWhiteList: false,
//       name: t("option.update"),
//       pattern: "/api/admin/roles/{roleId}",
//       method: "PUT",
//     },
//     {
//       tag: "system:role:delete",
//       type: "button",
//       isWhiteList: false,
//       name: t("option.delete"),
//       pattern: "/api/admin/roles/{roleId}",
//       method: "DELETE",
//     },
//     {
//       tag: "system:role:assign-permission",
//       type: "button",
//       isWhiteList: false,
//       name: t("option.assignPermission"),
//       pattern: "/api/admin/roleperms/{roleId}",
//       method: "PUT",
//     },
//     {
//       tag: "system:role:select-role-permission",
//       type: "button",
//       isWhiteList: false,
//       name: t("role.selectRolePermission"),
//       pattern: "/api/admin/roleperms/{roleId}",
//       method: "GET",
//     },
//     // {
//     //   tag: "system:role:sync-permission",
//     //   type: "button",
//     //   isWhiteList: false,
//     //   name: t("role.syncPermission"),
//     //   pattern: "/api/admin/permissions",
//     //   method: "POST"
//     // }
//   ],
// };
