import { t } from "@/i18n";
import type { MenuItem } from "../../menutype";
export const user: MenuItem = {
  tag: "system:user",
  leaf: true,
  path: "/users",
  type: "menu",
  isWhiteList: false,
  name: t("menu.user"),
  // icon: "el-icon-fa-user",
  children: [],
  permissions: [
    {
      tag: "system:user:search",
      type: "button",
      isWhiteList: false,
      name: t("option.query"),
      pattern: "/api/admin/users",
      method: "GET",
    },
    {
      tag: "system:user:insert",
      type: "button",
      isWhiteList: false,
      name: t("option.add"),
      pattern: "/api/admin/users",
      method: "POST",
    },
    {
      tag: "system:user:update",
      type: "button",
      isWhiteList: false,
      name: t("option.update"),
      pattern: "/api/admin/users/{userId}",
      method: "PUT",
    },
    {
      tag: "system:user:delete",
      type: "button",
      isWhiteList: false,
      name: t("option.delete"),
      pattern: "/api/admin/users/{userId}",
      method: "DELETE",
    },
    {
      tag: "system:user:assign-roles",
      type: "button",
      isWhiteList: false,
      name: t("option.assignRole"),
      pattern: "/api/admin/userroles/{userId}",
      method: "POST",
    },
    {
      tag: "system:user:reset-password",
      type: "button",
      isWhiteList: false,
      name: t("option.resetPassword"),
      pattern: "/api/admin/users/{userId}/passwordreset",
      method: "POST",
    },
  ],
};
// export default {
//   tag: "system:user",
//   leaf: true,
//   path: "/users",
//   type: "menu",
//   isWhiteList: false,
//   name: t("menu.user"),
//   // icon: "el-icon-fa-user",
//   options: [
//     {
//       tag: "system:user:select",
//       type: "button",
//       isWhiteList: false,
//       name: t("option.query"),
//       pattern: "/api/admin/users",
//       method: "GET",
//     },
//     {
//       tag: "system:user:insert",
//       type: "button",
//       isWhiteList: false,
//       name: t("option.add"),
//       pattern: "/api/admin/users",
//       method: "POST",
//     },
//     {
//       tag: "system:user:update",
//       type: "button",
//       isWhiteList: false,
//       name: t("option.update"),
//       pattern: "/api/admin/users/{userId}",
//       method: "PUT",
//     },
//     {
//       tag: "system:user:delete",
//       type: "button",
//       isWhiteList: false,
//       name: t("option.delete"),
//       pattern: "/api/admin/users/{userId}",
//       method: "DELETE",
//     },
//     {
//       tag: "system:user:assign-roles",
//       type: "button",
//       isWhiteList: false,
//       name: t("option.assignRole"),
//       pattern: "/api/admin/userroles/{userId}",
//       method: "POST",
//     },
//     {
//       tag: "system:user:reset-password",
//       type: "button",
//       isWhiteList: false,
//       name: t("option.resetPassword"),
//       pattern: "/api/admin/users/{userId}/passwordreset",
//       method: "POST",
//     },
//   ],
// };
