import { MenuItem } from "./../menutype";
import { t } from "@/i18n";
export const department: MenuItem = {
  tag: "department",
  leaf: true,
  path: "/department",
  type: "menu",
  isWhiteList: false,
  name: t("menu.department"),
  icon: "School",
  children: [],
  permissions: [
    {
      tag: "department:search",
      type: "button",
      isWhiteList: false,
      name: t("option.query"),
      pattern: "/api/admin/detainee/all",
      method: "GET",
    },
    {
      tag: "department:insert",
      type: "button",
      isWhiteList: false,
      name: t("option.add"),
      pattern: "/api/admin/department/create",
      method: "POST",
    },
    {
      tag: "department:update",
      type: "button",
      isWhiteList: false,
      name: t("option.update"),
      pattern: "/api/admin/detainee/update/{id}",
      method: "PUT",
    },
    {
      tag: "department:delete",
      type: "button",
      isWhiteList: false,
      name: t("option.delete"),
      pattern: "/api/admin/detainee/{id}",
      method: "DELETE",
    },
    {
      tag: "department:detail",
      type: "button",
      isWhiteList: false,
      name: t("option.detail"),
      pattern: "/api/admin/detainee/{id}",
      method: "GET",
    },
    {
      tag: "department:detail",
      type: "button",
      isWhiteList: false,
      name: t("option.detail"),
      pattern: "/api/admin/detainee/{id}",
      method: "GET",
    },
    {
      tag: "department::select:prison:all",
      type: "api",
      isWhiteList: false,
      name: t("option.query"),
      pattern: "/api/admin/detention-center/all",
      method: "GET",
    },
  ],
};
