import { MenuItem } from "./../menutype";
import { t } from "@/i18n";
export const detainee: MenuItem = {
  tag: "detainee",
  leaf: true,
  path: "/detainees",
  type: "menu",
  isWhiteList: false,
  name: t("menu.detainee"),
  icon: "User",
  children: [],
  permissions: [
    {
      tag: "detainee:search",
      type: "button",
      isWhiteList: false,
      name: t("option.query"),
      pattern: "/api/admin/detainee",
      method: "GET",
    },
    {
      tag: "detainee:insert",
      type: "button",
      isWhiteList: false,
      name: t("option.add"),
      pattern: "/api/admin/detainee/create",
      method: "POST",
    },
    {
      tag: "detainee:update",
      type: "button",
      isWhiteList: false,
      name: t("option.update"),
      pattern: "/api/admin/detainee/{id}",
      method: "PUT",
    },
    {
      tag: "detainee:delete",
      type: "button",
      isWhiteList: false,
      name: t("option.delete"),
      pattern: "/api/admin/detainee/{id}",
      method: "DELETE",
    },
    {
      tag: "detainee:detail",
      type: "button",
      isWhiteList: false,
      name: t("option.detail"),
      pattern: "/api/admin/detainee/{id}",
      method: "GET",
    },
    {
      tag: "detainee:select:province:all",
      type: "api",
      isWhiteList: false,
      name: t("option.query"),
      pattern: "/api/admin/province/all",
      method: "GET",
    },
    {
      tag: "detainee:select:detentionCenter:all",
      type: "api",
      isWhiteList: false,
      name: t("option.query"),
      pattern: "/api/admin/detention-center/all",
      method: "GET",
    },
    {
      tag: "detainee:select:ward:provinceCode",
      type: "api",
      isWhiteList: false,
      name: t("option.query"),
      pattern: "/api/admin/ward/{provinceCode}",
      method: "GET",
    },
    {
      tag: "detainee:select:ethnicity:all",
      type: "api",
      isWhiteList: false,
      name: t("option.query"),
      pattern: "/api/admin/ethnicity/all",
      method: "GET",
    },
    {
      tag: "detainee:select:religion:all",
      type: "api",
      isWhiteList: false,
      name: t("option.query"),
      pattern: "/api/admin/religion/all",
      method: "GET",
    },
    {
      tag: "detainee:select:country:all",
      type: "api",
      isWhiteList: false,
      name: t("option.query"),
      pattern: "/api/admin/country/all",
      method: "GET",
    },
  ],
};
// export default {
//   tag: "detainee",
//   leaf: true,
//   path: "/detainees",
//   type: "menu",
//   whiteList: false,
//   name: t("menu.detainee"),
//   icon: "el-icon-fa-users",
//   options: [],
// };
