import { t } from "@/i18n";
import { MenuItem } from "./../menutype";
// export default {
//   tag: "fingerprint-card",
//   leaf: true,
//   path: "/fingerprint",
//   type: "menu",
//   isWhiteList: false,
//   name: t("menu.fingerprint"),
//   icon: "el-icon-fa-users",
//   options: [],
// };
export const fingerprint: MenuItem = {
  tag: "fingerprint-card",
  leaf: true,
  path: "/fingerprint",
  type: "menu",
  isWhiteList: false,
  name: t("menu.fingerprint"),
  icon: "Pointer",
  children: [],
  permissions: [
    {
      tag: "fingerprint-card:search",
      type: "button",
      isWhiteList: false,
      name: t("option.query"),
      pattern: "/api/admin/fingerprint",
      method: "GET",
    },
    {
      tag: "fingerprint-card:insert",
      type: "button",
      isWhiteList: false,
      name: t("option.add"),
      pattern: "/api/admin/fingerprint/create",
      method: "POST",
    },
    {
      tag: "fingerprint-card:update",
      type: "button",
      isWhiteList: false,
      name: t("option.update"),
      pattern: "/api/admin/fingerprint/update/{id}",
      method: "PUT",
    },
    {
      tag: "fingerprint-card:delete",
      type: "button",
      isWhiteList: false,
      name: t("option.delete"),
      pattern: "/api/admin/fingerprint/{id}",
      method: "DELETE",
    },
    {
      tag: "fingerprint-card:detail",
      type: "api",
      isWhiteList: false,
      name: t("option.detail"),
      pattern: "/api/admin/fingerprint/{id}",
      method: "GET",
    },
    {
      tag: "fingerprint-card:select:detainee:all",
      type: "api",
      isWhiteList: false,
      name: t("option.query"),
      pattern: "/api/admin/detainee/all",
      method: "GET",
    },
  ],
};
