import { t } from "@/i18n";
import type { MenuItem } from "./../menutype";
export const report: MenuItem = {
  tag: "report",
  leaf: true,
  path: "/report",
  type: "menu",
  isWhiteList: false,
  name: t("menu.report"),
  icon: "List",
  children: [],
  permissions: [
    {
      tag: "report:view",
      type: "button",
      isWhiteList: false,
      name: t("option.view"),
      pattern: "/api/admin/reports/statistics/overview",
      method: "GET",
    },
    {
      tag: "report:detainee-by-status",
      type: "api",
      isWhiteList: false,
      name: t("option.query"),
      pattern: "/api/admin/reports/detainees-by-status",
      method: "GET",
    },
    {
      tag: "report:detainee-by-month",
      type: "api",
      isWhiteList: false,
      name: t("option.query"),
      pattern: "/api/admin/reports/monthly-trends",
      method: "GET",
    },
    {
      tag: "report:staff-by-department",
      type: "api",
      isWhiteList: false,
      name: t("option.query"),
      pattern: "/api/admin/reports/staff-by-department",
      method: "GET",
    },
    {
      tag: "report:identity-records",
      type: "api",
      isWhiteList: false,
      name: t("option.query"),
      pattern: "/api/admin/reports/identity-records",
      method: "GET",
    },
    {
      tag: "report:fingerprint-records",
      type: "api",
      isWhiteList: false,
      name: t("option.query"),
      pattern: "/api/admin/reports/fingerprint-cards",
      method: "GET",
    },
    // {
    //   tag: "report:generate",
    //   type: "button",
    //   isWhiteList: false,
    //   name: t("option.generate"),
    //   pattern: "/api/admin/report/generate",
    //   method: "POST",
    // },
    // {
    //   tag: "report:excel",
    //   type: "button",
    //   isWhiteList: false,
    //   name: t("option.excel"),
    //   pattern: "",
    //   method: null,
    // },
    // {
    //   tag: "report:pdf",
    //   type: "button",
    //   isWhiteList: false,
    //   name: t("option.pdf"),
    //   pattern: "",
    //   method: null,
    // },
    // {
    //   tag: "report:print",
    //   type: "button",
    //   isWhiteList: false,
    //   name: t("option.print"),
    //   pattern: "",
    //   method: null,
    // },
  ],
};
// export default {
//   tag: "report",
//   leaf: true,
//   path: "/report",
//   type: "menu",
//   isWhiteList: false,
//   name: t("menu.report"),
//   icon: "el-icon-s-custom",
//   options: [],
// };
