import { t } from "@/i18n";
import type { MenuItem } from "./../menutype";
export const staff: MenuItem = {
  tag: "staff",
  leaf: true,
  path: "/staff",
  type: "menu",
  isWhiteList: false,
  name: t("menu.staff"),
  icon: "Avatar",
  children: [],
  permissions: [
    {
      tag: "staff:search",
      type: "button",
      isWhiteList: false,
      name: t("option.query"),
      pattern: "/api/admin/staff",
      method: "GET",
    },
    {
      tag: "staff:insert",
      type: "button",
      isWhiteList: false,
      name: t("option.add"),
      pattern: "/api/admin/staff/create",
      method: "POST",
    },
    {
      tag: "staff:update",
      type: "button",
      isWhiteList: false,
      name: t("option.update"),
      pattern: "/api/admin/staff/update/{id}",
      method: "PUT",
    },
    {
      tag: "staff:delete",
      type: "button",
      isWhiteList: false,
      name: t("option.delete"),
      pattern: "/api/admin/staff/{id}",
      method: "DELETE",
    },
    {
      tag: "staff:select:id",
      type: "button",
      isWhiteList: false,
      name: t("option.query"),
      pattern: "/api/admin/staff/{id}",
      method: "GET",
    },
    {
      tag: "staff:select:position:all",
      type: "api",
      isWhiteList: false,
      name: t("option.query"),
      pattern: "/api/admin/position/all",
      method: "GET",
    },
    {
      tag: "staff:select:province:all",
      type: "api",
      isWhiteList: false,
      name: t("option.query"),
      pattern: "/api/admin/province/all",
      method: "GET",
    },
    {
      tag: "staff:select:prison:all",
      type: "api",
      isWhiteList: false,
      name: t("option.query"),
      pattern: "/api/admin/detention-center/all",
      method: "GET",
    },
    {
      tag: "staff:select:education:all",
      type: "api",
      isWhiteList: false,
      name: t("option.query"),
      pattern: "/api/admin/education-level/all",
      method: "GET",
    },
    {
      tag: "staff:select:ethnicity:all",
      type: "api",
      isWhiteList: false,
      name: t("option.query"),
      pattern: "/api/admin/ethnicity/all",
      method: "GET",
    },
    {
      tag: "staff:select:religion:all",
      type: "api",
      isWhiteList: false,
      name: t("option.query"),
      pattern: "/api/admin/religion/all",
      method: "GET",
    },
    {
      tag: "staff:select:ward:provinceCode",
      type: "api",
      isWhiteList: false,
      name: t("option.query"),
      pattern: "/api/admin/ward/{provinceCode}",
      method: "GET",
    },
  ],
};
// export default {
//   tag: "staff",
//   leaf: true,
//   path: "/staff",
//   type: "menu",
//   isWhiteList: false,
//   name: t("menu.staff"),
//   icon: "el-icon-s-custom",
//   options: [],
// };
