// @ts-ignore
import { t } from "@/i18n";
export default {
  tag: "system:user",
  leaf: true,
  path: "/users",
  type: "menu",
  whiteList: false,
  name: t("menu.user"),
  // icon: "el-icon-fa-user",
  options: [
    {
      tag: "system:user:select",
      type: "button",
      whiteList: false,
      name: t("option.query"),
      pattern: "/api/admin/users",
      method: "GET",
    },
    {
      tag: "system:user:insert",
      type: "button",
      whiteList: false,
      name: t("option.add"),
      pattern: "/api/admin/users",
      method: "POST",
    },
    {
      tag: "system:user:update",
      type: "button",
      whiteList: false,
      name: t("option.update"),
      pattern: "/api/admin/users/{userId}",
      method: "PUT",
    },
    {
      tag: "system:user:delete",
      type: "button",
      whiteList: false,
      name: t("option.delete"),
      pattern: "/api/admin/users/{userId}",
      method: "DELETE",
    },
    {
      tag: "system:user:assign-roles",
      type: "button",
      whiteList: false,
      name: t("option.assignRole"),
      pattern: "/api/admin/userroles/{userId}",
      method: "POST",
    },
    {
      tag: "system:user:reset-password",
      type: "button",
      whiteList: false,
      name: t("option.resetPassword"),
      pattern: "/api/admin/users/{userId}/passwordreset",
      method: "POST",
    },
  ],
};
